server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/neurogine}
    username: ${DB_USERNAME:neurogine}
    password: ${DB_PASSWORD:neurogine}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-env}
    expiration: ${JWT_EXP_SECONDS:86400}

logging:
  level:
    root: INFO
    com.neurogine.app: INFO
